# Site settings
title: Tekapo
email: zhaohq89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keep Calm and Blog On
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  lonelyswan

# Build settings
markdown: kramdown
